Issue # 2 | Render List Names and List Items
the-collab-lab/tcl-69-smart-shopping-list pull request #18
Opened 2024-02-05 19:15 UTC by piecanoe

## Description

This code renders List Names on Home and List Items on /list.

## Related Issue

Closes #2

## Acceptance Criteria

## Type of Changes

Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

## Updates

### Before

### After

## Testing Steps / QA Criteria

2024-02-06 17:46 UTC, amalyam commented on src/views/Home.jsx
> +				{data ? (
Seems like this ternary is reversed

2024-02-06 17:47 UTC, amalyam commented on src/views/List.jsx
> +				)}
This ternary also seems to be reversed

2024-02-06 17:48 UTC, amalyam requested changes
The two ternary statements both seem to be in reverse order

2024-02-06 18:20 UTC, krsnamara commented on src/views/Home.jsx
> +				{data ? (
Yes! It is. Will update that

2024-02-06 18:50 UTC, hsiangj commented
In the 'Notes' section in issue#2, it says there's a manual shopping list that could be used for rendering from issue#1. Perhaps this could be incorporated in List and List Items?

2024-02-06 22:14 UTC, krsnamara commented
We noticed that the list items appeared to be saved in local storage or cached somewhere. Upon log out the, navigation to /list will still show the list items. Assumption is there needs to be an "onSignOut" destroy or delete function added somewhere.

2024-02-07 01:11 UTC, amalyam commented on src/views/Home.jsx
> +				{data && data.length > 0 ? (
Nice double check here

2024-02-07 01:51 UTC, krsnamara approved these changes

2024-02-07 05:11 UTC, amalyam commented on src/views/List.jsx
> +				)}
Fix looks good, and also additional mapping!

2024-02-07 05:12 UTC, amalyam approved these changes
Fix on ternaries looks good!

2024-02-08 02:04 UTC, mxmason approved these changes
Works as expected, and great job on the fix!

2024-02-09 20:22 UTC, louieknolle approved these changes
Works as expected!

2024-02-10 19:48 UTC, merged