remove "Add your first item!" button
the-collab-lab/tcl-69-smart-shopping-list pull request #69
Opened 2024-03-28 20:26 UTC by amalyam

## Description

On the List page, remove the "Add your first item!" button, and make it clearer to the user that they should use the circular "+" button to add items. Do so by adding explainer text and possibly changing the position of the "+" button.

## Related Issue

Closes #68 
Sub-issue of #14 

## Acceptance Criteria

- [ ]  list page no longer has "Add your first item!" button
- [ ] additional text is added to make the function of the "+" button clearer
- [ ] adding items should only be done through the dialog box, not by directing the user to the Manage List page

## Updates

### Before

### After

## Testing Steps / QA Criteria

2024-03-28 23:28 UTC, hsiangj requested changes
My screen is a little smaller, and the button while closer than before, is showing on the footer:
<img width="1258" alt="Screen Shot 2024-03-28 at 4 23 11 PM" src="https://github.com/the-collab-lab/tcl-69-smart-shopping-list/assets/64502078/7cf0f83f-e58a-4c1a-b2cb-08fb823dbcd9">

And the button disappears when I shrink the screen:
<img width="489" alt="Screen Shot 2024-03-28 at 4 11 36 PM" src="https://github.com/the-collab-lab/tcl-69-smart-shopping-list/assets/64502078/e834ab31-780e-4994-b6ac-9e8775074f42">

I think the transform property in css might've shifted it off the page completely? 

Love the change in anticipation for color update. Minor note: I believe we will also be changing "+" to say "add."

2024-03-29 01:38 UTC, amalyam commented
Thanks for catching that @hsiangj !

After some discussion with and help from @mxmason in which we talked about how to make use of this button accessible, clear, and simple, I opted to remove the green (+) and instead have a consistent "Add Item" button next to the "Share List" button. This ensures that the button will not obscure item text, is in a consistent location, and does not depend on color for the user to identify it.

2024-03-29 23:50 UTC, hsiangj approved these changes
Thanks for the update, modal works as it did before!

2024-04-01 15:40 UTC, louieknolle approved these changes
Works as expected and I agree that the simpler, persistent Add Item button is a good alternative.

2024-04-01 16:30 UTC, amalyam commented
@piecanoe @krsnamara wanted to get your thoughts before I merge because this changes some key layout features that we'd talked about (and didn't want to overwrite Marty's work before discussing!)

2024-04-01 17:53 UTC, merged

2024-04-01 17:55 UTC, amalyam commented
Merged with current design, future update will have a better combination of design and accessibility